CREATE TABLE IF NOT EXISTS airpol (
    id VARCHAR(10) PRIMARY KEY NOT NULL,
    country VARCHAR(25) UNIQUE,
    city VARCHAR(25),
    latitude REAL UNIQUE,
    longitude REAL UNIQUE,
    population INT,
    date_time TIMESTAMP,
    year INT,
    month VARCHAR(15),
    day INT,
    weekday VARCHAR(15),
    air_quality VARCHAR(15),
    air_index INT,
    o3 REAL,
    nh3 REAL,
    co REAL,
    no REAL,
    no2 REAL,
    so2 REAL,
    pm2_5 REAL,
    pm10 REAL
)